---
cyp:
  priority: 100
  iso_code: CYP
  name: Cypriot pound
  symbol: "£"
  alternate_symbols: []
  subunit: Cent
  subunit_to_unit: 100
  symbol_first: true
  html_entity: "&#x00A3;"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '196'
  smallest_denomination: 1
eek:
  priority: 100
  iso_code: EEK
  name: Estonian Kroon
  symbol: KR
  alternate_symbols: []
  subunit: Sent
  subunit_to_unit: 100
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '233'
  smallest_denomination: 5
ghc:
  priority: 100
  iso_code: GHC
  name: Ghanaian Cedi
  symbol: "₵"
  disambiguate_symbol: GH₵
  alternate_symbols:
  - GH₵
  subunit: Pesewa
  subunit_to_unit: 100
  symbol_first: true
  html_entity: "&#x20B5;"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '288'
  smallest_denomination: 1
mro:
  priority: 100
  iso_code: MRO
  name: Mauritanian Ouguiya
  symbol: UM
  disambiguate_symbol: MRO
  alternate_symbols: []
  subunit: Khoums
  subunit_to_unit: 5
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '478'
  smallest_denomination: 1
mtl:
  priority: 100
  iso_code: MTL
  name: Maltese Lira
  symbol: "₤"
  alternate_symbols:
  - Lm
  subunit: Cent
  subunit_to_unit: 100
  symbol_first: true
  html_entity: "&#x00A3;"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '470'
  smallest_denomination: 1
std:
  priority: 100
  iso_code: STD
  name: São Tomé and Príncipe Dobra
  symbol: Db
  alternate_symbols: []
  subunit: Cêntimo
  subunit_to_unit: 100
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '678'
  smallest_denomination: 10000
tmm:
  priority: 100
  iso_code: TMM
  name: Turkmenistani Manat
  symbol: m
  alternate_symbols: []
  subunit: Tennesi
  subunit_to_unit: 100
  symbol_first: false
  html_entity: ''
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '795'
  smallest_denomination: 1
VEB:
  priority: 100
  iso_code: VEB
  name: Venezuelan Bolívar
  symbol: Bs.
  alternate_symbols: []
  subunit: Céntimo
  subunit_to_unit: 100
  symbol_first: true
  html_entity: ''
  decimal_mark: ","
  thousands_separator: "."
  iso_numeric: '862'
  smallest_denomination: 1
vef:
  priority: 100
  iso_code: VEF
  name: Venezuelan Bolívar fuerte
  symbol: Bs.F.
  alternate_symbols: []
  subunit: Céntimo
  subunit_to_unit: 100
  symbol_first: true
  html_entity: ''
  decimal_mark: ","
  thousands_separator: "."
  iso_numeric: '937'
  smallest_denomination: 1
zwd:
  priority: 100
  iso_code: ZWD
  name: Zimbabwean Dollar
  symbol: "$"
  disambiguate_symbol: ZWD
  alternate_symbols:
  - Z$
  subunit: Cent
  subunit_to_unit: 100
  symbol_first: true
  html_entity: "$"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '716'
  smallest_denomination: 100
zwl:
  priority: 100
  iso_code: ZWL
  name: Zimbabwean Dollar
  symbol: "$"
  disambiguate_symbol: ZWL
  alternate_symbols:
  - Z$
  subunit: Cent
  subunit_to_unit: 100
  symbol_first: true
  html_entity: "$"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '932'
  smallest_denomination: 100
zwn:
  priority: 100
  iso_code: ZWN
  name: Zimbabwean Dollar
  symbol: "$"
  disambiguate_symbol: ZWN
  alternate_symbols:
  - Z$
  subunit: Cent
  subunit_to_unit: 100
  symbol_first: true
  html_entity: "$"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '942'
  smallest_denomination: 100
zwr:
  priority: 100
  iso_code: ZWR
  name: Zimbabwean Dollar
  symbol: "$"
  disambiguate_symbol: ZWR
  alternate_symbols:
  - Z$
  subunit: Cent
  subunit_to_unit: 100
  symbol_first: true
  html_entity: "$"
  decimal_mark: "."
  thousands_separator: ","
  iso_numeric: '935'
  smallest_denomination: 100
